export const categories = [
  {
    id: 13,
    title: "TV & FILM",
    path: "/category/tv-and-film",
    icon: "/icons/chip/tv-and-film.svg",
    color: "#ef3e68",
  },
  {
    id: 12,
    title: "FOOD",
    path: "/category/food",
    icon: "/icons/chip/food.svg",
    color: "#f9a524",
  },
  {
    id: 11,
    title: "THEATER & ARTS",
    path: "/category/theater-and-the-arts",
    icon: "/icons/chip/theater-and-the-arts.svg",
    color: "#755489",
  },
  {
    id: 4,
    title: "MUSIC",
    path: "/category/music",
    icon: "/icons/chip/music.svg",
    color: "#b5c932",
  },
  {
    id: 243,
    title: "HYPE",
    path: "/category/hype",
    icon: "/icons/chip/hype.svg",
    color: "#d63ba3",
  },
  {
    id: 242,
    title: "HUB",
    path: "/category/hub",
    icon: "/icons/chip/hub.svg",
    color: "#3dbb95",
  },
  {
    id: 244,
    title: "EXPOSÉ",
    path: "/category/expose",
    icon: "/icons/chip/expose.svg",
    color: "#f6B50b",
  },
];
